// Authentic Real Saudi Companies & Universities Database for MAYDAN (ميدان)
// Features "القصيم (بريدة) - حضوري" for Smart Methods Co. & TECH AND TEACH

window.MAYDAN_MOCK = {
  companyInfo: {
    name: "شركة الأساليب الذكية (Smart Methods Co.)",
    nameEn: "Smart Methods Co.",
    logo: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png",
    industry: "الحلول التقنية المتقدمة والأنظمة الذكية",
    industryEn: "Advanced Tech Solutions & Smart Systems",
    location: "القصيم (بريدة) - حضوري",
    locationEn: "Qassim (Buraidah) - On-site",
    metrics: {
      publishedOpportunities: 5,
      totalApplications: 46,
      shortlistedCandidates: 14,
      suggestedMatches: 24
    }
  },

  realCompanies: [
    {
      id: "comp-smart-methods",
      name: "شركة الأساليب الذكية (Smart Methods)",
      nameEn: "Smart Methods Co.",
      industry: "الحلول التقنية والأنظمة الذكية",
      industryEn: "Tech Solutions & Smart Systems",
      city: "القصيم",
      cityEn: "Qassim",
      area: "بريدة - حضوري",
      areaEn: "Buraidah - On-site",
      workType: "حضوري",
      workTypeEn: "On-site",
      description: "شركة تقنية سعودية رائدة متخصصة في تطوير الأنظمة المدمجة والحلول الذكية وتصميم الرقائق الرقمية وتطبيقات البرمجة بمنطقة القصيم.",
      descriptionEn: "A leading Saudi tech company specializing in embedded systems development, smart solutions, digital chip design, and programming applications in the Qassim region.",
      activity: "تطوير الحلول الرقمية، البرمجة المدمجة، محاكاة الرقائق المعالجة، وأتمتة النظم التجارية.",
      activityEn: "Digital solutions development, embedded programming, processor chip simulation, and business system automation.",
      fields: ["هندسة الحاسب", "علوم الحاسب", "الذكاء الاصطناعي", "تحليل البيانات"],
      fieldsEn: ["Computer Engineering", "Computer Science", "Artificial Intelligence", "Data Analytics"],
      website: "https://smartmethods.sa",
      linkedin: "https://www.linkedin.com/company/%D8%A7%D9%84%D8%A3%D8%B3%D8%A7%D9%84%D9%8A%D8%A8-%D8%A7%D9%84%D8%B0%D9%83%D9%8A%D8%A9-smart-methods/",
      logo: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png"
    },
    {
      id: "comp-tech-teach",
      name: "شركة تيك آند تيتش (TECH AND TEACH)",
      nameEn: "TECH AND TEACH Co.",
      industry: "تقنيات التعليم وتطوير العتاد الرقمي",
      industryEn: "EdTech & Digital Hardware Development",
      city: "القصيم",
      cityEn: "Qassim",
      area: "بريدة - حضوري",
      areaEn: "Buraidah - On-site",
      workType: "حضوري",
      workTypeEn: "On-site",
      description: "شركة متخصصة في تصميم الأنظمة الميكروإلكترونية والمنصات التعليمية المتقدمة واختبار الرقائق الرقمية.",
      descriptionEn: "A company specializing in microelectronic system design, advanced educational platforms, and digital chip testing.",
      activity: "تصميم الرقائق الرقمية بلغات Verilog/VHDL، اختبار البرمجيات التعليمية، وتطوير الأنظمة المدمجة.",
      activityEn: "Digital chip design with Verilog/VHDL, educational software testing, and embedded systems development.",
      fields: ["هندسة الحاسب", "تصميم الرقائق RTL", "الأنظمة المدمجة", "هندسة البرمجيات"],
      fieldsEn: ["Computer Engineering", "RTL Chip Design", "Embedded Systems", "Software Engineering"],
      website: "https://techandteach.sa",
      linkedin: "https://www.linkedin.com/company/techandteachsa",
      logo: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png"
    },
    {
      id: "comp-elm",
      name: "شركة علم (Elm)",
      nameEn: "Elm Company",
      industry: "الخدمات الرقمية والحلول الإلكرونية",
      industryEn: "Digital Services & E-Solutions",
      city: "الرياض",
      cityEn: "Riyadh",
      area: "حي الملقا",
      areaEn: "Al-Malqa District",
      workType: "هجين",
      workTypeEn: "Hybrid",
      description: "شركة مملوكة للصندوق الاستثماري تمكّن التحول الرقمي للقطاعات الحكومية والخاصة بالمملكة.",
      descriptionEn: "An investment fund-owned company enabling digital transformation for government and private sectors across Saudi Arabia.",
      activity: "تطوير المنصات الوطنية، نماذج الذكاء الاصطناعي التنبؤية، وإدارة قواعد البيانات الضخمة.",
      activityEn: "National platform development, predictive AI models, and large-scale database management.",
      fields: ["علم البيانات", "الذكاء الاصطناعي", "هندسة البرمجيات", "الأمن السيبراني"],
      fieldsEn: ["Data Science", "Artificial Intelligence", "Software Engineering", "Cybersecurity"],
      website: "https://elm.sa",
      linkedin: "https://www.linkedin.com/company/elm",
      logo: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png"
    },
    {
      id: "comp-stc",
      name: "solutions by stc",
      nameEn: "solutions by stc",
      industry: "الاتصالات والتحول الرقمي",
      industryEn: "Telecom & Digital Transformation",
      city: "الرياض",
      cityEn: "Riyadh",
      area: "مجمع المنيع التقني",
      areaEn: "Al-Munee Tech Complex",
      workType: "حضوري",
      workTypeEn: "On-site",
      description: "مزود الحلول التقنية الأول بالمملكة لتقديم حلول الحوسبة السحابية وتحليل البيانات والأمن السيبراني.",
      descriptionEn: "Saudi Arabia's leading tech solutions provider for cloud computing, data analytics, and cybersecurity solutions.",
      activity: "بناء البنى التحتية السحابية، أتمتة العمليات الرقمية، وتحليل أداء الشبكات.",
      activityEn: "Cloud infrastructure building, digital process automation, and network performance analysis.",
      fields: ["الحوسبة السحابية", "نظم المعلومات", "تحليل البيانات", "هندسة الشبكات"],
      fieldsEn: ["Cloud Computing", "Information Systems", "Data Analytics", "Network Engineering"],
      website: "https://solutions.com.sa",
      linkedin: "https://www.linkedin.com/company/solutionsbystc",
      logo: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png"
    },
    {
      id: "comp-watania",
      name: "شركة دواجن الوطنية (Al-Watania)",
      nameEn: "Al-Watania Poultry Co.",
      industry: "الأغذية والأنظمة اللوجستية الميدانية",
      industryEn: "Food & Field Logistics Systems",
      city: "القصيم",
      cityEn: "Qassim",
      area: "عيون الجواء / بريدة",
      areaEn: "Uyun Al-Jawa / Buraidah",
      workType: "حضوري",
      workTypeEn: "On-site",
      description: "أكبر منشأة لوجستية وغذائية بالقصيم تعتمد على التقنيات الحديثة في تتبع سلاسل الإمداد وأتمتة الإنتاج.",
      descriptionEn: "The largest logistics and food facility in Qassim, leveraging modern technologies for supply chain tracking and production automation.",
      activity: "أتمتة خطوط الإنتاج، تتبع سلاسل الإمداد بالذكاء الاصطناعي، وتحليل بيانات المبيعات والتوزيع.",
      activityEn: "Production line automation, AI-powered supply chain tracking, and sales & distribution data analysis.",
      fields: ["نظم المعلومات اللوجستية", "تحليل البيانات", "الهندسة الميكانيكية/الكهربائية"],
      fieldsEn: ["Logistics Information Systems", "Data Analytics", "Mechanical/Electrical Engineering"],
      website: "https://al-watania.com",
      logo: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png"
    }
  ],

  initialProposals: [
    {
      id: "prop-101",
      studentId: "student-1",
      studentName: "حنين هيثم القصير",
      studentMajor: "هندسة الحاسب",
      studentUniversity: "جامعة القصيم",
      studentAvatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      studentLinkedin: "https://www.linkedin.com/in/haneen-al-qassir-b68aa4387",
      studentGithub: "https://github.com/EngHaneena",
      companyId: "comp-smart-methods",
      companyName: "شركة الأساليب الذكية (Smart Methods)",
      title: "تصميم الرقائق الرقمية وبناء لوحة تحليلات الذكاء الاصطناعي",
      titleEn: "Digital Chip Design & AI Analytics Dashboard",
      description: "بناء وتطوير محاكي منطقي متقدم للرقائق والمعالجات المعالجة بلغة Verilog و C++ بالإضافة للوحة مؤشرات تفاعلية بالذكاء الاصطناعي.",
      descriptionEn: "Building and developing an advanced logic simulator for digital chips and processors using Verilog & C++, along with an interactive AI-powered indicators dashboard.",
      value: "توفير وقت إعداد التقارير بنسبة 60% وتسهيل تطوير واختبار الدوائر الإلكترونية بالشركة بالقصيم.",
      valueEn: "Saving 60% of reporting preparation time and streamlining electronic circuit development and testing at the company in Qassim.",
      skills: ["Python", "C++", "Verilog/VHDL", "Digital Logic", "AI"],
      duration: "12 أسبوع",
      durationEn: "12 Weeks",
      message: "السلام عليكم ورحمة الله، أود تقديم هذا المقترح العملي للاستفادة من شغفي وهندستي في الحاسب لتطوير بيئة محاكاة الرقائق والأنظمة بالقصيم.",
      messageEn: "Hello, I would like to submit this practical proposal to leverage my passion and computer engineering skills to develop a chip and systems simulation environment in Qassim.",
      matchScore: 99,
      status: "قيد المراجعة",
      statusEn: "Under Review",
      createdAt: "2026-08-16"
    },
    {
      id: "prop-102",
      studentId: "student-2",
      studentName: "رولا العثيم",
      studentMajor: "علوم الحاسب",
      studentUniversity: "جامعة القصيم",
      studentAvatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      studentLinkedin: "https://www.linkedin.com/in/rola-alothaim-5792a2338/",
      companyId: "comp-smart-methods",
      companyName: "شركة الأساليب الذكية (Smart Methods)",
      title: "تحليل بيانات العملاء وبناء لوحة مؤشرات أداء تفاعلية",
      titleEn: "Customer Data Analysis & Interactive KPI Dashboard",
      description: "بناء لوحة تحكم تفاعلية متقدمة باستخدام Power BI و SQL لتصفية بيانات العملاء والأنشطة التجارية بالشركة وتحليل السلوك الشرائي بالقصيم.",
      descriptionEn: "Building an advanced interactive dashboard using Power BI & SQL to filter customer data and business activities, and analyze purchasing behavior in Qassim.",
      value: "توفير وقت إعداد التقارير بنسبة 60% ومساعدة فريق الإدارة بالشركة على اتخاذ قرارات استراتيجية مبنية على البيانات الميدانية.",
      valueEn: "Saving 60% of reporting time and helping the management team make data-driven strategic decisions.",
      skills: ["Python", "SQL", "Power BI", "Data Analysis"],
      duration: "12 أسبوع",
      durationEn: "12 Weeks",
      message: "السلام عليكم ورحمة الله، أود تقديم هذا المقترح العملي للاستفادة من مهارتي في تحليل البيانات لتطوير لوحة مؤشرات تفاعلية تخدم نشاط الشركة بالقصيم.",
      messageEn: "Hello, I would like to submit this practical proposal to apply my data analytics skills to develop an interactive KPI dashboard serving the company's operations in Qassim.",
      matchScore: 96,
      status: "مهتم",
      statusEn: "Interested",
      createdAt: "2026-08-16"
    },
    {
      id: "prop-103",
      studentId: "student-3",
      studentName: "وئام عبدالله",
      studentMajor: "هندسة الحاسب",
      studentUniversity: "جامعة القصيم",
      studentAvatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      studentLinkedin: "https://www.linkedin.com/in/weaam-abdullah-27b50632b/",
      companyId: "comp-smart-methods",
      companyName: "شركة الأساليب الذكية (Smart Methods)",
      title: "تطوير برمجيات الأنظمة المدمجة ومحاكاة الرقائق الإلكترونية",
      titleEn: "Embedded Systems Software Development & Chip Simulation",
      description: "بناء وتطوير حلول برمجة مدمجة واختبار منطق الرقائق الرقمية المعالجة بلغة Verilog و C++ لتطوير بيئة العمل بالشركة.",
      descriptionEn: "Building and developing embedded programming solutions and testing digital chip logic using Verilog & C++ to enhance the company's work environment.",
      value: "رفع كفاءة المعالجة بالشركة وتخفيض الأخطاء التشغيلية بنسبة 50% وتسهيل تجربة المعالجة الرقمية.",
      valueEn: "Increasing processing efficiency and reducing operational errors by 50% while streamlining the digital processing experience.",
      skills: ["Python", "C++", "Verilog", "Embedded Systems"],
      duration: "12 أسبوع",
      durationEn: "12 Weeks",
      message: "السلام عليكم ورحمة الله، أود تقديم هذا المقترح الميداني للاستفادة من شغفي في هندسة الحاسب والأنظمة المدمجة لخدمة نشاط الشركة بالقصيم.",
      messageEn: "Hello, I would like to submit this field proposal to leverage my passion for computer engineering and embedded systems to serve the company's operations in Qassim.",
      matchScore: 95,
      status: "قيد المراجعة",
      statusEn: "Under Review",
      createdAt: "2026-08-16"
    }
  ],

  students: [
    {
      id: "student-1",
      name: "حنين هيثم القصير",
      nameEn: "Haneen Haytham Al-Kaseer",
      title: "طالبة هندسة حاسب - جامعة القصيم",
      titleEn: "Computer Engineering Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "هندسة الحاسب",
      majorEn: "Computer Engineering",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.92 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالبة هندسة حاسب بجامعة القصيم شغوفة بتصميم الرقائق الرقمية والأنظمة المدمجة والذكاء الاصطناعي وتطوير البرمجيات.",
      bioEn: "Computer Engineering student at Qassim University, passionate about digital chip design, embedded systems, AI, and software development.",
      linkedin: "https://www.linkedin.com/in/haneen-al-qassir-b68aa4387",
      github: "https://github.com/EngHaneena",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      skills: ["Python", "C++", "Verilog/VHDL", "Digital Logic", "SQL", "Data Analysis", "AI", "React"],
      projects: [
        { name: "Digital Chip Logic Simulator", desc: "محاكي منطقي للرقائق الرقمية المعالجة والمعالجات الصغيرة بلغة Verilog و C++", descEn: "A logic simulator for digital processor chips and microprocessors using Verilog & C++" },
        { name: "AI Chatbot", desc: "مساعد ذكي للإجابة على الاستفسارات الأكاديمية بجامعة القصيم باستخدام برمجيات NLP", descEn: "An AI assistant for answering academic inquiries at Qassim University using NLP" },
        { name: "Data Analysis Dashboard", desc: "لوحة تحكم تفاعلية لتحليل سلوك مستخدمي التطبيقات", descEn: "An interactive dashboard for analyzing app user behavior" }
      ],
      certifications: ["AWS Certified Cloud Practitioner", "Digital Systems & Embedded Architecture"],
      cvUploaded: true,
      cvName: "Haneen_Haytham_AlKaseer_CV.pdf"
    },
    {
      id: "student-2",
      name: "رولا العثيم",
      nameEn: "Rola Al-Othaim",
      title: "طالبة علوم حاسب - جامعة القصيم",
      titleEn: "Computer Science Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "علوم الحاسب",
      majorEn: "Computer Science",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.91 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالبة علوم حاسب بجامعة القصيم متخصصة في الذكاء الاصطناعي وتنقيب البيانات وتحليل السلوك الرقمي للمنشآت.",
      bioEn: "Computer Science student at Qassim University specializing in artificial intelligence, data mining, and digital behavior analysis for organizations.",
      linkedin: "https://www.linkedin.com/in/rola-alothaim-5792a2338/",
      github: "https://github.com/rola-alothaim",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      skills: ["Python", "Machine Learning", "SQL", "Power BI", "Data Analysis"],
      projects: [
        { name: "Business Insights Dashboard", desc: "لوحة تحكم تفاعلية متقدمة لتصفية بيانات العملاء وسلوك الشراء", descEn: "An advanced interactive dashboard for filtering customer data and purchasing behavior" }
      ],
      certifications: ["TensorFlow Developer Certificate"],
      cvUploaded: true,
      cvName: "Rola_AlOthaim_CV.pdf"
    },
    {
      id: "student-3",
      name: "وئام عبدالله",
      nameEn: "Weaam Abdullah",
      title: "طالبة هندسة حاسب - جامعة القصيم",
      titleEn: "Computer Engineering Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "هندسة الحاسب",
      majorEn: "Computer Engineering",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.95 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالبة هندسة حاسب بجامعة القصيم شغوفة بتطوير الأنظمة المدمجة وتصميم الرقائق الرقمية والذكاء الاصطناعي وتطوير البرمجيات.",
      bioEn: "Computer Engineering student at Qassim University passionate about embedded systems development, digital chip design, AI, and software development.",
      linkedin: "https://www.linkedin.com/in/weaam-abdullah-27b50632b/",
      github: "https://github.com/weaam-abdullah",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      skills: ["Python", "C++", "Verilog/VHDL", "Digital Logic", "Embedded Systems", "AI", "SQL"],
      projects: [
        { name: "Microprocessor Logic Simulator", desc: "محاكي منطقي للمعالجات والرقائق المعالجة بلغة Verilog و C++", descEn: "A logic simulator for microprocessors and chips using Verilog & C++" },
        { name: "Embedded Smart Sensors Platform", desc: "نظام مدمج لقراءة وتحليل الحساسات الرقمية بالقصيم", descEn: "An embedded system for reading and analyzing digital sensors in Qassim" }
      ],
      certifications: ["AWS Certified Cloud Practitioner", "Digital Systems Architecture"],
      cvUploaded: true,
      cvName: "Weaam_Abdullah_Qassim_University_CV.pdf"
    },
    {
      id: "student-4",
      name: "كيان القفاري",
      nameEn: "Kayan Al-Geffari",
      title: "طالبة هندسة برمجيات - جامعة القصيم",
      titleEn: "Software Engineering Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "هندسة البرمجيات",
      majorEn: "Software Engineering",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.88 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالبة هندسة برمجيات بجامعة القصيم مهتمة بتصميم واجهات المستخدم المتجاوبة UI/UX وتطوير المنصات الرقمية وتكامل واجهات APIs.",
      bioEn: "Software Engineering student at Qassim University interested in responsive UI/UX design, digital platform development, and API integration.",
      linkedin: "https://www.linkedin.com/in/kayan-algeffari-7b2b63263/",
      github: "https://github.com/Kaya1n",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      skills: ["React", "UI/UX", "JavaScript", "REST APIs", "Python"],
      projects: [
        { name: "Interactive Web Portal", desc: "منصة تفاعلية عالية السلاسة لإدارة التفاعلات والمستندات الرقمية", descEn: "A high-performance interactive platform for managing digital interactions and documents" }
      ],
      certifications: ["Full Stack Web Development Certificate"],
      cvUploaded: true,
      cvName: "Kayan_AlGeffari_CV.pdf"
    },
    {
      id: "student-5",
      name: "سنا ادلبي",
      nameEn: "Sana Al-Edilbi",
      title: "طالبة هندسة حاسب - جامعة القصيم",
      titleEn: "Computer Engineering Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "هندسة الحاسب",
      majorEn: "Computer Engineering",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.86 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالبة هندسة حاسب بجامعة القصيم شغوفة بالرقائق الرقمية والأنظمة المدمجة والأمن السيبراني وتصميم المعالجات.",
      bioEn: "Computer Engineering student at Qassim University passionate about digital chips, embedded systems, cybersecurity, and processor design.",
      linkedin: "https://www.linkedin.com/in/sana-aledilbi/",
      github: "https://github.com/sana-aledilbi",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      skills: ["C++", "Python", "Verilog/VHDL", "Cybersecurity", "Embedded Systems"],
      projects: [
        { name: "Secure Chip Verification Logic", desc: "منطق واختبار سلامة الرقائق والمعالجات الإلكترونية لمنع الاختراق", descEn: "Logic and safety testing for electronic chips and processors to prevent intrusion" }
      ],
      certifications: ["CompTIA Security+", "Embedded Hardware Architecture"],
      cvUploaded: true,
      cvName: "Sana_AlEdilbi_CV.pdf"
    },
    {
      id: "student-6",
      name: "سنا البيطار",
      nameEn: "Sana Al-Bettar",
      title: "طالبة علوم حاسب - جامعة القصيم",
      titleEn: "Computer Science Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "علوم الحاسب",
      majorEn: "Computer Science",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.84 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالبة علوم حاسب بجامعة القصيم متخصصة في تطبيقات الذكاء الاصطناعي وبناء النماذج اللغوية وتحليل البيانات الضخمة.",
      bioEn: "Computer Science student at Qassim University specializing in AI applications, language model building, and big data analysis.",
      linkedin: "https://www.linkedin.com/in/sana-al-bettar-828161397/",
      github: "https://github.com/sana-albettar",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_university_student_woman_wearing_a_hijab/screen.png",
      skills: ["Python", "AI", "NLP", "Machine Learning", "SQL"],
      projects: [
        { name: "AI Customer Support Assistant", desc: "مساعد ذكي للإجابة على استفسارات العملاء باللغة العربية", descEn: "An AI assistant for answering customer inquiries in Arabic" }
      ],
      certifications: ["AI & Data Science Professional Certificate"],
      cvUploaded: true,
      cvName: "Sana_AlBettar_CV.pdf"
    },
    {
      id: "student-7",
      name: "فهد إبراهيم التويجري",
      nameEn: "Fahad Ibrahim Al-Tuwaijri",
      title: "طالب هندسة حاسب - جامعة القصيم",
      titleEn: "Computer Engineering Student - Qassim University",
      university: "جامعة القصيم (Qassim University)",
      major: "هندسة الحاسب",
      majorEn: "Computer Engineering",
      level: "سنة تخرج (Senior)",
      levelEn: "Senior Year",
      gpa: "3.90 / 4.00",
      city: "القصيم (بريدة)",
      cityEn: "Qassim (Buraidah)",
      bio: "طالب هندسة حاسب بجامعة القصيم متقدم في الأنظمة المدمجة والذكاء الاصطناعي وتصميم الرقائق الرقمية وتطبيقات البرمجة بلغة C++ و Verilog بالقصيم.",
      bioEn: "Computer Engineering student at Qassim University advanced in embedded systems, AI, digital chip design, and programming in C++ & Verilog.",
      linkedin: "https://linkedin.com/in/fahad-altuwaijri",
      github: "https://github.com/fahad-altuwaijri",
      avatar: "stitch_maydan_ai_powered_co_op_platform/ultra_minimalist_faceless_avatar_of_a_company_representative_clean_geometric/screen.png",
      skills: ["C++", "Python", "Verilog/VHDL", "Embedded Systems", "Linux", "SQL", "AI"],
      projects: [
        { name: "Embedded Smart Sensors Simulator", desc: "نظام أتمتة ومحاكاة الحساسات الرقمية للأنظمة المدمجة بمنطقة القصيم", descEn: "An automation and simulation system for digital sensors in embedded systems in Qassim" },
        { name: "AI Traffic Flow Optimizer in Buraidah", desc: "نموذج ذكاء اصطناعي ورؤية حاسوبية لتحليل وتقييم الكثافة المرورية بمدينة بريدة", descEn: "An AI and computer vision model for analyzing and evaluating traffic density in Buraidah" }
      ],
      certifications: ["NVIDIA Deep Learning Certificate", "Embedded Systems & IoT Architecture"],
      cvUploaded: true,
      cvName: "Fahad_AlTuwaijri_CV.pdf"
    }
  ],

  initialOpportunities: [
    {
      id: "opp-tech-teach",
      title: "Digital Chip Design & Microelectronics",
      titleAr: "تصميم الرقائق الرقمية والأنظمة الدقيقة (Chip Design)",
      category: "Semiconductors & Hardware",
      categoryAr: "تصميم الرقائق والأنظمة الرقمية",
      duration: "8 Weeks (Summer Internship)",
      durationAr: "8 أسابيع (تدريب صيفي)",
      company: "شركة تيك آند تيتش (TECH AND TEACH)",
      location: "القصيم (بريدة) - حضوري",
      locationEn: "Qassim (Buraidah) - On-site",
      workType: "حضوري",
      workTypeEn: "On-site",
      stipend: "تُحدد بعد توقيع العقد",
      stipendEn: "To be determined after signing the contract",
      applicantsCount: 14,
      publishedDate: "جديد اليوم",
      publishedDateEn: "New Today",
      skills: ["Verilog/VHDL", "Digital Logic", "FPGA", "C++", "Embedded Systems"],
      majors: ["Computer Engineering", "Electrical Engineering"],
      description: "تعلن شركة تيك آند تيتش (TECH AND TEACH) في القصيم (بريدة - حضوري) عن فرصة تدريب صيفي نوعية ومتقدمة في مجال تصميم الرقائق الرقمية (Digital Chip Design & Microelectronics)، وتصميم الدوائر المتكاملة واختبارها على لوحات FPGA.",
      descriptionEn: "TECH AND TEACH in Qassim (Buraidah - On-site) announces a distinctive summer internship opportunity in the field of Digital Chip Design & Microelectronics, covering integrated circuit design and testing on FPGA boards.",
      responsibilities: [
        "تصميم ومحاكاة المنطق الرقمي (Digital Logic RTL Synthesis) بلغة Verilog / VHDL بمقر الشركة الحضوري في القصيم (بريدة)",
        "تطبيق واختبار النماذج الأولية للرقائق الرقمية المعالجة على لوحات FPGA في المختبر",
        "التحقق من التوقيت والبرمجة منخفضة المستوى للدوائر المتكاملة",
        "إعداد تقارير الاختبار والمحاكاة التقنية لشركة TECH AND TEACH"
      ],
      responsibilitiesEn: [
        "Design and simulate Digital Logic (RTL Synthesis) using Verilog/VHDL at the company's on-site office in Qassim (Buraidah)",
        "Implement and test digital chip prototypes on FPGA boards in the lab",
        "Verify timing and low-level programming of integrated circuits",
        "Prepare technical simulation and test reports for TECH AND TEACH"
      ],
      deliverables: [
        "نموذج تصميم رقيقة رقمية واختبارها على لوحة FPGA (Digital Chip Prototype)",
        "تقرير اختبار المحاكاة وتوثيق RTL Architecture"
      ],
      deliverablesEn: [
        "A digital chip design prototype tested on an FPGA board",
        "Simulation test report and RTL Architecture documentation"
      ],
      isAiGenerated: true,
      status: "نشطة",
      statusEn: "Active"
    },
    {
      id: "opp-1",
      title: "Customer Insights Dashboard",
      titleAr: "تحليل بيانات العملاء ونظم اللوحات الذكية",
      category: "Data Analytics",
      categoryAr: "تحليل البيانات",
      duration: "8 Weeks (Summer Internship)",
      durationAr: "8 أسابيع (تدريب صيفي)",
      company: "شركة الأساليب الذكية (Smart Methods)",
      location: "القصيم (بريدة) - حضوري",
      locationEn: "Qassim (Buraidah) - On-site",
      workType: "حضوري",
      workTypeEn: "On-site",
      stipend: "تُحدد بعد توقيع العقد",
      stipendEn: "To be determined after signing the contract",
      applicantsCount: 32,
      publishedDate: "منذ يومين",
      publishedDateEn: "2 Days Ago",
      skills: ["Python", "SQL", "Power BI", "Data Analysis"],
      majors: ["Computer Science", "Computer Engineering", "Information Systems", "Data Science"],
      description: "تعلن شركة الأساليب الذكية (Smart Methods) في القصيم (بريدة - حضوري) عن فرصة تدريب صيفي متميزة في قسم تحليل البيانات الضخمة، لبناء لوحة تحكم تفاعلية توضح سلوك العملاء والمبيعات للمساعدة في اتخاذ القرارات الاستراتيجية.",
      descriptionEn: "Smart Methods in Qassim (Buraidah - On-site) announces a distinguished summer internship in the Big Data Analytics division to build an interactive dashboard showing customer behavior and sales to support strategic decision-making.",
      responsibilities: [
        "تحليل بيانات المعاملات الرقمية والعملاء بمقر شركة الأساليب الذكية الحضوري في القصيم (بريدة)",
        "بناء لوحة تحكم تفاعلية باستخدام Power BI و SQL",
        "استخراج مؤشرات الأداء الرئيسية (KPIs) وسلوك المستخدمين",
        "تقديم التقارير والتوصيات الذكية لفريق القيادة في الأساليب الذكية"
      ],
      responsibilitiesEn: [
        "Analyze digital transaction and customer data at Smart Methods' on-site office in Qassim (Buraidah)",
        "Build an interactive dashboard using Power BI & SQL",
        "Extract key performance indicators (KPIs) and user behavior insights",
        "Present smart reports and recommendations to the Smart Methods leadership team"
      ],
      deliverables: [
        "لوحة تحكم تفاعلية مكتملة (Smart Methods Customer Dashboard)",
        "تقرير تحليلي شاملاً لأنماط وسلوك العملاء",
        "عرض توثيق البيانات والتقرير النهائي"
      ],
      deliverablesEn: [
        "A complete interactive dashboard (Smart Methods Customer Dashboard)",
        "A comprehensive analytical report on customer patterns and behavior",
        "Data documentation presentation and final report"
      ],
      isAiGenerated: true,
      status: "نشطة",
      statusEn: "Active"
    },
    {
      id: "opp-2",
      title: "AI Customer Support Assistant",
      titleAr: "مساعد خدمة العملاء الذكي باللغة العربية",
      category: "Artificial Intelligence",
      categoryAr: "الذكاء الاصطناعي",
      duration: "8 Weeks (Summer Internship)",
      durationAr: "8 أسابيع (تدريب صيفي)",
      company: "solutions by stc",
      location: "الرياض (مجمع المنيع التقني / عن بُعد)",
      locationEn: "Riyadh (Al-Munee Tech Complex / Remote)",
      workType: "هجين",
      workTypeEn: "Hybrid",
      stipend: "تُحدد بعد توقيع العقد",
      stipendEn: "To be determined after signing the contract",
      applicantsCount: 22,
      publishedDate: "منذ 4 أيام",
      publishedDateEn: "4 Days Ago",
      skills: ["Python", "NLP", "Machine Learning"],
      majors: ["Computer Engineering", "Computer Science", "Artificial Intelligence"],
      description: "مشروع تدريب صيفي متميز لدى solutions by stc لبناء واختبار مساعد ذكي يعتمد على نماذج المعالجة اللغوية العربية لتحسين استجابة دعم العملاء.",
      descriptionEn: "A distinguished summer internship project at solutions by stc to build and test an AI assistant based on Arabic NLP models to improve customer support response.",
      responsibilities: [
        "تدريب واختبار نماذج المعالجة اللغوية للغة العربية (Arabic NLP)",
        "ربط واجهات برمجة التطبيقات (APIs) مع أنظمة الدعم الفني لشركة stc solutions",
        "تقييم دقة الإجابات وتحسين الأداء التشغيلي"
      ],
      responsibilitiesEn: [
        "Train and test Arabic Natural Language Processing (NLP) models",
        "Integrate APIs with stc solutions technical support systems",
        "Evaluate answer accuracy and improve operational performance"
      ],
      deliverables: [
        "نموذج عملي لمساعد الذكاء الاصطناعي",
        "دليل الربط البرمجي والنتائج الميدانية"
      ],
      deliverablesEn: [
        "A functional AI assistant prototype",
        "API integration guide and field results documentation"
      ],
      isAiGenerated: true,
      status: "نشطة",
      statusEn: "Active"
    },
    {
      id: "opp-3",
      title: "Industrial IoT & Data Monitoring",
      titleAr: "نظام مراقبة البيانات والمستشعرات الصناعية",
      category: "Data Analytics / IoT",
      categoryAr: "تحليل البيانات والإنترنت الصناعي",
      duration: "8 Weeks (Summer Internship)",
      durationAr: "8 أسابيع (تدريب صيفي)",
      company: "شركة دواجن الوطنية (Al-Watania)",
      location: "القصيم (بريدة / عيون الجواء) - حضوري",
      locationEn: "Qassim (Buraidah / Uyun Al-Jawa) - On-site",
      workType: "حضوري",
      workTypeEn: "On-site",
      stipend: "تُحدد بعد توقيع العقد",
      stipendEn: "To be determined after signing the contract",
      applicantsCount: 16,
      publishedDate: "منذ أسبوع",
      publishedDateEn: "1 Week Ago",
      skills: ["Python", "SQL", "Data Analysis", "IoT Sensors"],
      majors: ["Computer Engineering", "Computer Science", "Information Systems"],
      description: "فرصة تدريب صيفي متميزة بشركة دواجن الوطنية بالقصيم للعمل على تحليل بيانات المستشعرات الصناعية والمراقبة الذكية لخطوط الإنتاج.",
      descriptionEn: "A distinguished summer internship opportunity at Al-Watania Poultry in Qassim to work on industrial sensor data analysis and smart monitoring of production lines.",
      responsibilities: [
        "تحليل بيانات مستشعرات الحرارة والإنتاجية بمرافق الوطنية بالقصيم",
        "تنظيف البيانات وتجهيز تقارير التنبؤ بالأعطال التشغيلية",
        "بناء Dashboards متابعة فورية للإدارة التشغيلية"
      ],
      responsibilitiesEn: [
        "Analyze temperature and productivity sensor data at Al-Watania facilities in Qassim",
        "Clean data and prepare operational fault prediction reports",
        "Build real-time monitoring dashboards for operational management"
      ],
      deliverables: [
        "نظام متابعة وتنبؤ بالبيانات الصناعية",
        "تقرير تحليل الأداء التشغيلي بالقصيم"
      ],
      deliverablesEn: [
        "An industrial data monitoring and prediction system",
        "Operational performance analysis report for Qassim"
      ],
      isAiGenerated: false,
      status: "نشطة",
      statusEn: "Active"
    },
    {
      id: "opp-5",
      title: "Smart Recommendation Engine",
      titleAr: "خوارزمية التوصيات الذكية لخدمات الأعمال",
      category: "AI / Data Science",
      categoryAr: "الذكاء الاصطناعي وعلم البيانات",
      duration: "8 Weeks (Summer Internship)",
      durationAr: "8 أسابيع (تدريب صيفي)",
      company: "شركة ثقة لخدمات الأعمال (Thiqah)",
      location: "الرياض (طريق الملك فهد)",
      locationEn: "Riyadh (King Fahd Road)",
      workType: "حضوري",
      workTypeEn: "On-site",
      stipend: "تُحدد بعد توقيع العقد",
      stipendEn: "To be determined after signing the contract",
      applicantsCount: 25,
      publishedDate: "منذ 5 أيام",
      publishedDateEn: "5 Days Ago",
      skills: ["Python", "Machine Learning", "Data Analysis"],
      majors: ["Computer Science", "Data Science"],
      description: "بناء خوارزمية توصيات ذكية لدى شركة ثقة بالرياض لترشيح الخدمات الإلكترونية الأكثر ملاءمة لقطاع الأعمال والمنشآت.",
      descriptionEn: "Building a smart recommendation algorithm at Thiqah in Riyadh to suggest the most suitable digital services for businesses and organizations.",
      responsibilities: [
        "تحليل سجلات واستخدام المنشآت لخدمات ثقة الرقمية بالرياض",
        "تطبيق خوارزميات التصفية التعاونية (Collaborative Filtering)",
        "دمج خوارزمية التوصية في بيئة اختبار سحابية"
      ],
      responsibilitiesEn: [
        "Analyze organization usage logs of Thiqah's digital services in Riyadh",
        "Apply Collaborative Filtering algorithms",
        "Integrate the recommendation algorithm into a cloud testing environment"
      ],
      deliverables: [
        "خوارزمية التوصيات الذكية المكتملة",
        "تقرير اختبار المحاكاة واختبارات الأداء"
      ],
      deliverablesEn: [
        "A complete smart recommendation algorithm",
        "Simulation test report and performance benchmarks"
      ],
      isAiGenerated: false,
      status: "نشطة",
      statusEn: "Active"
    }
  ],

  initialApplications: [
    {
      id: "app-100",
      opportunityId: "opp-tech-teach",
      studentId: "student-1",
      studentName: "حنين هيثم القصير",
      opportunityTitle: "Digital Chip Design & Microelectronics",
      companyName: "شركة تيك آند تيتش (TECH AND TEACH)",
      matchScore: 95,
      appliedDate: "2026-08-15",
      status: "مرشح",
      statusEn: "Shortlisted",
      message: "أنا حنين هيثم القصير، طالبة هندسة حاسب بجامعة القصيم ولديا شغف كبير بالتدريب الصيفي الحضوري في مجال تصميم الرقائق الرقمية ببريدة!"
    },
    {
      id: "app-101",
      opportunityId: "opp-1",
      studentId: "student-1",
      studentName: "حنين هيثم القصير",
      opportunityTitle: "Customer Insights Dashboard",
      companyName: "شركة الأساليب الذكية (Smart Methods)",
      matchScore: 92,
      appliedDate: "2026-08-14",
      status: "قيد المراجعة",
      statusEn: "Under Review",
      message: "أنا طالبة هندسة حاسب بجامعة القصيم ومتحمسة للتقديم على التدريب الصيفي الحضوري بمقر شركة الأساليب الذكية في بريدة!"
    },
    {
      id: "app-102",
      opportunityId: "opp-2",
      studentId: "student-1",
      studentName: "حنين هيثم القصير",
      opportunityTitle: "AI Customer Support Assistant",
      companyName: "solutions by stc",
      matchScore: 88,
      appliedDate: "2026-08-12",
      status: "مرشح",
      statusEn: "Shortlisted",
      message: "عملت سابقًا على مشروع NLP باللغة العربية وأتطلع للمساهمة في بناء مساعد الذكاء الاصطناعي لشركة stc solutions."
    }
  ]
};

// Aliases for seamless access
window.MAYDAN_MOCK.opportunities = window.MAYDAN_MOCK.initialOpportunities;
window.MAYDAN_MOCK.applications = window.MAYDAN_MOCK.initialApplications;
window.MAYDAN_MOCK.proposals = window.MAYDAN_MOCK.initialProposals;
window.MAYDAN_MOCK.challenges = window.MAYDAN_MOCK.initialCompanyChallenges;
